// <auto-generated />
using System;
using InfoSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241022092730_Initial create")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoSystem.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<decimal>("BeloppIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeloppUt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CarReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalBeloppIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBeloppUt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DriverID");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverID = 1,
                            BeloppIn = 0m,
                            BeloppUt = 100m,
                            CarReg = "ABC123",
                            DriverName = "Emma Nilsson",
                            NoteDate = new DateTime(2024, 8, 22, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7459),
                            NoteDescription = "Added to System",
                            ResponsibleEmployee = "Alice Johnson",
                            TotalBeloppIn = 0m,
                            TotalBeloppUt = 100m
                        },
                        new
                        {
                            DriverID = 2,
                            BeloppIn = 0m,
                            BeloppUt = 150m,
                            CarReg = "XYZ987",
                            DriverName = "Per Karlsson",
                            NoteDate = new DateTime(2024, 9, 22, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7546),
                            NoteDescription = "Added to System",
                            ResponsibleEmployee = "Bob Smith",
                            TotalBeloppIn = 0m,
                            TotalBeloppUt = 150m
                        },
                        new
                        {
                            DriverID = 3,
                            BeloppIn = 150m,
                            BeloppUt = 0m,
                            CarReg = "ATZ127",
                            DriverName = "Olle Persson",
                            NoteDate = new DateTime(2024, 9, 22, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7553),
                            NoteDescription = "Added to System",
                            ResponsibleEmployee = "Bob Smith",
                            TotalBeloppIn = 150m,
                            TotalBeloppUt = 0m
                        });
                });

            modelBuilder.Entity("InfoSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "alice@info.com",
                            Name = "Alice Johnson",
                            Password = "password123",
                            Role = "Employee"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "bob@info.com",
                            Name = "Bob Smith",
                            Password = "password234",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("InfoSystem.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<decimal>("BeloppIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeloppUt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventID");

                    b.HasIndex("DriverID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            BeloppIn = 0m,
                            BeloppUt = 100m,
                            DriverID = 1,
                            NoteDate = new DateTime(2024, 10, 12, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7589),
                            NoteDescription = "Speeding violation"
                        },
                        new
                        {
                            EventID = 2,
                            BeloppIn = 0m,
                            BeloppUt = 50m,
                            DriverID = 1,
                            NoteDate = new DateTime(2024, 10, 2, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7597),
                            NoteDescription = "Routine maintenance"
                        },
                        new
                        {
                            EventID = 3,
                            BeloppIn = 0m,
                            BeloppUt = 100m,
                            DriverID = 2,
                            NoteDate = new DateTime(2024, 10, 17, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7601),
                            NoteDescription = "Tire replacement"
                        },
                        new
                        {
                            EventID = 4,
                            BeloppIn = 150m,
                            BeloppUt = 0m,
                            DriverID = 3,
                            NoteDate = new DateTime(2024, 10, 19, 11, 27, 29, 654, DateTimeKind.Local).AddTicks(7606),
                            NoteDescription = "Package deliverd"
                        });
                });

            modelBuilder.Entity("InfoSystem.Models.Event", b =>
                {
                    b.HasOne("InfoSystem.Models.Driver", "Driver")
                        .WithMany("Events")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("InfoSystem.Models.Driver", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
